version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FinanceBot"
s3_prefix = "FinanceBot"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
resolve_s3 = true
confirm_changeset = true
