AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Finance-Bot

Globals:
  Function:
    Timeout: 3
    Runtime: python3.12
    Tags:
      project: "Finance-Bot"
    Architectures:
      - arm64
    LoggingConfig:
      LogGroup: !Sub /aws/lambda/${AWS::StackName}
      LogFormat: JSON

Resources:
  FinanceBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: finance_bot/
      Handler: bot_lambda.lambda_handler
      FunctionUrlConfig:
        AuthType: NONE
      ReservedConcurrentExecutions: 1
      Timeout: 30
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "secretsmanager:GetSecretValue"
              Resource:
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:FinanceBot/Secret-*"
      Environment:
        Variables:
          SECRETS: !Sub "{{resolve:secretsmanager:FinanceBot/Secret}}"
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:553035198032:layer:git-lambda2:8"

Outputs:
  TelegramApi:
    Description: "Lambda Function URL for Finance Bot"
    Value:
      Fn::GetAtt: FinanceBotFunctionUrl.FunctionUrl
